### ISSUE TITLE
MySQL 1.35.0 - incorrect bounce rate and average visit time

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#1328]
Now that charts are working again with MySQL (thanks !),
Umami always shows 100% bounce rate and 0s average visit time.

**Comment by mikecao** [comment]
Fixed in v1.36.0

**Comment by yibudak** [comment]
Still exist in v1.36.0
@mikecao
![image](https://user-images.githubusercontent.com/52182279/180988558-f7f87566-bef9-49a7-9f40-dd3d4cfc68f4.png)

**Comment by mikecao** [comment]
It depends on how many hits you have. 100% bounce rate is not always an error. If you have 10 hits and they all bounce that’s 100%.
