### ISSUE TITLE
Cannot update since v1.33.1

### ISSUE THREAD

**Issue by Lennart01** [umami-software/umami#1333]
Hey, I use docker-compose and since 1.33.1 I can't update anymore.
Executing `docker-compose pull` and `docker-compose up -d --force-recreate ` doesn't update my version number in the web panel anymore.
This has always worked beforehand. Is the docked image not updated?
I use the default docker-compose.yml.
Really like the project thanks for your great work :).

**Comment by mikecao** [comment]
We had an error in the last version where we had the wrong version number. It should be fixed in the latest v1.36.0

**Comment by cirrusflyer** [comment]
I just tried to pull new images and still shows me at 1.33.1.  What am I missing?  Thanks

**Comment by Lennart01** [comment]
> I just tried to pull new images and still shows me at 1.33.1. What am I missing? Thanks
Can confirm. Same issue here

**Comment by Lennart01** [comment]
@cirrusflyer are you using this image in your docker-compose.yml ?
`ghcr.io/mikecao/umami:postgresql-latest`

**Comment by cirrusflyer** [comment]
Yes, but my install wasn't mission critical, so I just started completely over and working now.

**Comment by mathieulesniak** [comment]
Got the same issue, but found the solution : 
My docker-compose file was referring to 
`ghcr.io/mikecao/umami`
but now, docker images are hosted on `umami-software` org, instead of `mikecao` account.
Just replace base docker image path with this line, and it should be ok : 
`ghcr.io/umami-software/umami`

**Comment by Lennart01** [comment]
Solution:
Replace `ghcr.io/mikecao/umami:postgresql-latest` with `ghcr.io/umami-software/umami:postgresql-latest`
in your docker-compose.yml.
