### ISSUE TITLE
Cannot destructure property 'session_id' of 'session' as it is null.

### ISSUE THREAD

**Issue by korzhyk** [umami-software/umami#1340]
![image](https://user-images.githubusercontent.com/1100134/180637433-26771229-538c-41b1-be66-5c5d2f87e36c.png)

I also got this error in my instance
```
2022-07-24T05:17:13.978 app[664c49c9] fra [info] TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
2022-07-24T05:17:13.978 app[664c49c9] fra [info] at getSession (/app/.next/server/chunks/1649.js:228:13)
2022-07-24T05:17:13.978 app[664c49c9] fra [info] at async /app/.next/server/chunks/1649.js:41:19
2022-07-24T06:28:03.101 app[664c49c9] fra [info] TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
2022-07-24T06:28:03.101 app[664c49c9] fra [info] at getSession (/app/.next/server/chunks/1649.js:228:13)
2022-07-24T06:28:03.101 app[664c49c9] fra [info] at async /app/.next/server/chunks/1649.js:41:19
```

There `session` for some reason can be `null` https://github.com/umami-software/umami/blob/15ae4569c5c082b50d9a322f382396f4d2d08aa1/lib/session.js#L63

**Comment by korzhyk** [comment]
Looks like problem in exception `catch`
https://github.com/umami-software/umami/blob/15ae4569c5c082b50d9a322f382396f4d2d08aa1/lib/session.js#L56-L60

**Comment by KevinVR** [comment]
The same thing is happening on umami.is the official website. The /api/collect POST is failing with a 500, with that exact error.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/2247829/180662424-2a9ac207-ed5a-446b-a801-370b9d3d9fa4.png">

**Comment by KevinVR** [comment]
I've debugged it locally and was able to get some more info. When you trigger a POST twice, with the same user agent, but without a session ID in the request, it will fail.

```
db_1     | 2022-07-24 22:02:40.585 UTC [65] ERROR:  duplicate key value violates unique constraint "session.session_uuid_unique"
db_1     | 2022-07-24 22:02:40.585 UTC [65] DETAIL:  Key (session_uuid)=(96e5965a-0bd2-548e-b201-08814c2fd116) already exists.
db_1     | 2022-07-24 22:02:40.585 UTC [65] STATEMENT:  INSERT INTO "public"."session" ("session_uuid","website_id","created_at","hostname","browser","os","screen","language","device") VALUES ($1,$2,$3,$4,$5,$6,$7,
$8,$9) RETURNING "public"."session"."session_id"
umami_1  | TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
umami_1  |     at getSession (/app/.next/server/chunks/1649.js:229:13)
umami_1  |     at async /app/.next/server/chunks/1649.js:41:19
```

It seems this session ID is supposed to be sent the second time using the X-UMAMI-CACHE header, but it is not being sent. The first time, the JWT gets generated successfully though, eg: 

`eyJhbGciOiJIUzI1NiJ9.eyJ3ZWJzaXRlX2lkIjoxLCJzZXNzaW9uX2lkIjo0LCJpYXQiOjE2NTg3MDAwNjZ9.ojBUhXnGbi1G4kO_c2OF_WeIx-uTHtjkay3uLNrHAwE`

```
{
  "website_id": 1,
  "session_id": 4,
  "iat": 1658700066
}
```

Now I don't know how the front-end is supposed to send this back if it exists.

In any case, if the user-agent and all details match a previous record, shouldn't that be allowed? It could be the session id is not in the cache anymore.

**Comment by briancao** [comment]
This bug was created during Clickhouse implementation.  Have a PR to fix it.

https://github.com/umami-software/umami/pull/1343

**Comment by KevinVR** [comment]
> This bug was created during Clickhouse implementation. Have a PR to fix it.
> 
> #1343

Ah you were faster than me  😁 I just made a pull request as well. Let's get this fixed!

**Comment by KevinVR** [comment]
@korzhyk this issue can be closed, fixed in 1.36.1 - just tested and working!

**Comment by ben182** [comment]
The issue remains for me on 1.36.1, Node v18.6.0, fresh install, empty db
```js
    at async /home/ploi/domain.test/.next/server/chunks/1649.js:41:19
    at getSession (/home/ploi/domain.test/.next/server/chunks/1649.js:229:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at async /home/ploi/domain.test/.next/server/chunks/1649.js:41:19
    at getSession (/home/ploi/domain.test/.next/server/chunks/1649.js:229:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at async /home/ploi/domain.test/.next/server/chunks/1649.js:41:19
    at getSession (/home/ploi/domain.test/.next/server/chunks/1649.js:229:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at async /home/ploi/domain.test/.next/server/chunks/1649.js:41:19
    at getSession (/home/ploi/domain.test/.next/server/chunks/1649.js:229:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
    at async /home/ploi/domain.test/.next/server/chunks/1649.js:41:19
    at getSession (/home/ploi/domain.test/.next/server/chunks/1649.js:229:13)
TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
}
  meta: { field_name: 'session_id' }
  clientVersion: '3.15.2',
  code: 'P2003',
    at RequestHandler.request (/home/ploi/domain.test/node_modules/@prisma/client/runtime/index.js:49022:15) {
PrismaClientKnownRequestError: Foreign key constraint failed on the field: `session_id`
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
warn  - You have enabled experimental feature(s).
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
warn  - You have enabled experimental feature(s).
}
  ]
    '/home/ploi/domain.test/node_modules/next/dist/bin/next'
    '/home/ploi/domain.test/node_modules/next/dist/cli/next-start.js',
    '/home/ploi/domain.test/node_modules/next/dist/server/lib/start-server.js',
    '/home/ploi/domain.test/node_modules/next/dist/server/next.js',
    '/home/ploi/domain.test/node_modules/next/dist/server/next-server.js',
    '/home/ploi/domain.test/node_modules/next/dist/server/require.js',
  requireStack: [
  code: 'MODULE_NOT_FOUND',
    at async NextNodeServer.pipe (/home/ploi/domain.test/node_modules/next/dist/server/base-server.js:623:25) {
    at NextNodeServer.renderErrorToResponse (/home/ploi/domain.test/node_modules/next/dist/server/base-server.js:1165:37)
    at NextNodeServer.findPageComponents (/home/ploi/domain.test/node_modules/next/dist/server/next-server.js:429:63)
    at Object.loadComponents (/home/ploi/domain.test/node_modules/next/dist/server/load-components.js:58:23)
    at Object.requirePage (/home/ploi/domain.test/node_modules/next/dist/server/require.js:48:12)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.mod._resolveFilename (/home/ploi/domain.test/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
- /home/ploi/domain.test/node_modules/next/dist/bin/next
```

**Comment by taylor-stein** [comment]
I've updated to 1.36.1, however I still see these errors coming across my deployment console. That being said, I don't see these errors when inspecting any of the `collect` Network events from my site. 
![image](https://user-images.githubusercontent.com/59148531/182227885-cd83c577-c8bf-45ce-b972-76fb157deb18.png)

**Comment by brycied00d** [comment]
I've just updated to 1.37.0 (from 1.36.1) and I'm still seeing this sporadically, both the Umami log and Postgres logging the constraint violation. It wasn't clear to me from looking at the PRs whether this specifically affects the server-side or the `umami.js` that's embedded.

Is this issue triggered from `umami.js` itself? I'm wondering if clients/browsers that still have the old, pre-upgrade `umami.js` loaded would be responsible, in which case I'll disregard these errors for a day or two until all caches are refreshed, or whether this issue is ongoing/regressed?

I'm not able to trigger these errors myself when I browse my sites, but evidently other visitors are.
```
postgres_1  | 2022-08-11 17:29:25.002 UTC [36] ERROR:  duplicate key value violates unique constraint "session_session_uuid_key"
postgres_1  | 2022-08-11 17:29:25.002 UTC [36] DETAIL:  Key (session_uuid)=(6a737998-f85a-56f3-ba1c-20862718b713) already exists.
postgres_1  | 2022-08-11 17:29:25.002 UTC [36] STATEMENT:  INSERT INTO "public"."session" ("session_uuid","website_id","created_at","hostname","browser","os","device","screen","language","country") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "public"."session"."session_id"
umami_1     | TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
umami_1     |     at getSession (/app/.next/server/chunks/1649.js:228:13)
umami_1     |     at async /app/.next/server/chunks/1649.js:41:19
postgres_1  | 2022-08-11 17:36:27.999 UTC [65] ERROR:  duplicate key value violates unique constraint "session_session_uuid_key"
postgres_1  | 2022-08-11 17:36:27.999 UTC [65] DETAIL:  Key (session_uuid)=(1b96052a-de2f-5145-8844-3e4588df2c2c) already exists.
postgres_1  | 2022-08-11 17:36:27.999 UTC [65] STATEMENT:  INSERT INTO "public"."session" ("session_uuid","website_id","created_at","hostname","browser","os","device","screen","language","country") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "public"."session"."session_id"
umami_1     | TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
umami_1     |     at getSession (/app/.next/server/chunks/1649.js:228:13)
umami_1     |     at async /app/.next/server/chunks/1649.js:41:19
postgres_1  | 2022-08-11 17:36:43.592 UTC [39] ERROR:  duplicate key value violates unique constraint "session_session_uuid_key"
postgres_1  | 2022-08-11 17:36:43.592 UTC [39] DETAIL:  Key (session_uuid)=(c5969e8d-096a-5212-8fe6-35f0240eef55) already exists.
postgres_1  | 2022-08-11 17:36:43.592 UTC [39] STATEMENT:  INSERT INTO "public"."session" ("session_uuid","website_id","created_at","hostname","browser","os","device","screen","language","country") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "public"."session"."session_id"
umami_1     | TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
umami_1     |     at getSession (/app/.next/server/chunks/1649.js:228:13)
umami_1     |     at async /app/.next/server/chunks/1649.js:41:19
postgres_1  | 2022-08-11 17:40:03.442 UTC [39] ERROR:  duplicate key value violates unique constraint "session_session_uuid_key"
postgres_1  | 2022-08-11 17:40:03.442 UTC [39] DETAIL:  Key (session_uuid)=(1b5ce572-cdd0-5b88-9e35-b13bd8b0f45a) already exists.
postgres_1  | 2022-08-11 17:40:03.442 UTC [39] STATEMENT:  INSERT INTO "public"."session" ("session_uuid","website_id","created_at","hostname","browser","os","device","screen","language","country") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "public"."session"."session_id"
umami_1     | TypeError: Cannot destructure property 'session_id' of 'session' as it is null.
umami_1     |     at getSession (/app/.next/server/chunks/1649.js:228:13)
umami_1     |     at async /app/.next/server/chunks/1649.js:41:19
```

**Comment by korzhyk** [comment]
@briancao I think https://github.com/umami-software/umami/issues/1340#issuecomment-1193267350 that check of error type is fails. As we can see actual error from postgres!? has a lowercase `unique constraint`

**Comment by mikecao** [comment]
Yes we need to update the error message check, thanks @korzhyk.

**Comment by czottmann** [comment]
I get the same error, all the time, across all my sites, even at the first hit. I've tried different browsers, cleared local data etc., to no avail.  That means at the moment Umami isn't tracking anything at all for me.

**Comment by mikecao** [comment]
This bug only happens when two or more hits come in rapid succession. The error `duplicate key value violates unique constraint "session_session_uuid_key"` means the session was already created. It should actually affect your stats since the first session would have been recorded. Not sure what is going on with your case @czottmann. What are you specs, where are you hosted?

**Comment by czottmann** [comment]
@mikecao It's running on Vercel+Supabase.  Latest version, I'm at 8f0e84f right now. I've upgraded from 1.36.1, the migration failed, which I've fixed after checking the output of `yarn check-db` (there were some indexes missing, apparently).
