### ISSUE TITLE
Make logo link or remove pointer style.

### ISSUE THREAD

**Issue by dev-nicolaos** [umami-software/umami#2015]
### Describe the Bug

Currently, the logo in the top left of [the navbar gets `cursor: pointer`](https://github.com/umami-software/umami/blob/586529a5ca2913f43a9b14a45ea65f99164abd61/components/layout/NavBar.module.css#L30) suggesting to the user that its a link. [But its not](https://github.com/umami-software/umami/blob/586529a5ca2913f43a9b14a45ea65f99164abd61/components/layout/NavBar.js#L29), so the user clicks it and is confused when nothing happens. Either the logo should be made a link or the misleading style should be removed.

I'm happy to open a pull request, just not sure what's the desired behavior.

### Database

MySQL

**Comment by uncenter** [comment]
It is a link, and it redirects to the root URL. The root URL redirects to `/dashboard`, so that might be the cause of the confusion if you were clicking it while on the dashboard.

**Comment by uncenter** [comment]
> > Ah the logo? I'm not seeing any `cursor: pointer;` on the rendered page even though it is in the module styles like you pointed you.
> 
> I'm seeing it in both Firefox and Chromium based browsers.

On the logo or on the text?

Here's the HTML for it:

```html
<div class="CompanyLogo_logo__qw6G6">
   <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 428 389.11">
      <g data-name="Layer 2">
         <g data-name="Layer 4">
            <circle cx="214.15" cy="181" r="171" fill="#fff" stroke="#000" stroke-miterlimit="10" stroke-width="20"></circle>
            <path d="M413 134.11H15.29a15 15 0 00-15 15v15.3C.12 168 0 171.52 0 175.11c0 118.19 95.81 214 214 214 116.4 0 211.1-92.94 213.93-208.67 0-.44.07-.88.07-1.33v-30a15 15 0 00-15-15z"></path>
         </g>
      </g>
   </svg>
   <a href="/">umami</a>
</div>
```

I'm getting a `cursor: pointer;` on the "umami" text, a link (probably the browser stylesheet), but not on the icon.

**Comment by franciscao633** [comment]
The pointer will be removed, since it is no longer a hyperlink to avoid confusion.

**Comment by franciscao633** [comment]
fixed in v2.3.0

**Comment by JakubJeziorski** [comment]
this is still present in the "
![image](https://github.com/umami-software/umami/assets/32456116/8a34ae66-7154-4ab7-a1ba-e6c11f8d082c)
"
Logo Umami in those previews redirects to Umami main website. My Umami is self hosted.

**Comment by uncenter** [comment]
@JakubJeziorski The point of this issue is that the logo wasn't actually a link but appeared to be. It is a link now I guess, but what is your issue with it? Where would you like the link to go? I think it should go to the Umami main website so someone else can use Umami if they like it.
