### ISSUE TITLE
Page crash it says [@formatjs/intl] An `id` must be provided to format a message.

### ISSUE THREAD

**Issue by Innei** [umami-software/umami#2113]
### Describe the Bug

I can't visit umami dashboard. Got error

[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at r (https://analyze.innei.ren/_next/static/chunks/pages/_app-0e67ddf2180faf84.js:1:150)
    at m (https://analyze.innei.ren/_next/static/chunks/pages/_app-0e67ddf2180faf84.js:6:546061)
    at Y (https://analyze.innei.ren/_next/static/chunks/pages/_app-0e67ddf2180faf84.js:6:555082)
    at I (https://analyze.innei.ren/_next/static/chunks/968-104b6020f0922c66.js:1:5015)
    at ab (https://analyze.innei.ren/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:60915)
    at ud (https://analyze.innei.ren/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:72801)
    at i (https://analyze.innei.ren/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:120370)
    at oO (https://analyze.innei.ren/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:99112)
    at https://analyze.innei.ren/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98979
    at oF (https://analyze.innei.ren/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98986)

### Database

PostgreSQL

**Comment by ImYrS** [comment]
same as you

**Comment by ImYrS** [comment]
@Innei fixed by updating to the latest version

**Comment by ImYrS** [comment]
> what version are you using?

It was happened in v2.2.0 on my server, and fixed by updated to v2.3.0

**Comment by gavinhewitt** [comment]
> > what version are you using?
> 
> It was happened in v2.2.0 on my server, and fixed by updated to v2.3.0

Silly question but what steps do you need to take? I've done `yarn upgrade umami`, which finished without problems, but still seeing the same error.

**Comment by Rabithua** [comment]
I have also updated to the latest version, and it appears that the issue has been fixed. However, I am not certain.

**Comment by kskan** [comment]
I encountered this problem too. I can't use the dashboard for anything, throw the error:[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue

**Comment by wangel13** [comment]
Same, update fixed it.

**Comment by gavinhewitt** [comment]
Update fixed it, but now it's back again :-(

**Comment by wangel13** [comment]
I think it's connected with [this code](https://github.com/umami-software/umami/blob/master/components/common/UpdateNotice.js#L42) because there is no such constant, `messages.newVersionAvailable` in file [/components/messages.js](https://github.com/umami-software/umami/blob/master/components/messages.js). And when a new release comes out, the translation system crashes.

**Comment by wangel13** [comment]
[Here](https://github.com/umami-software/umami/commit/5262d19c8b2b8a6b93b302082326d8f06f138a6e#diff-7212c5fae79b1f07b9b9dc97c7ef9cc093f6ceb4bfd6e49640e016ec9ed4e1d1R181) it's added. But [here](https://github.com/umami-software/umami/commit/8a9532f21372f4a2aa5910ae4e45ad542be4731a#diff-7212c5fae79b1f07b9b9dc97c7ef9cc093f6ceb4bfd6e49640e016ec9ed4e1d1L186) it's deleted.

**Comment by wangel13** [comment]
https://github.com/umami-software/umami/pull/2126

**Comment by Innei** [comment]
Updated to solve. Closed.

**Comment by nicolasramy** [comment]
Hi,
I got the same issue on version 2.2.0. After deleting the cookies and Localstorage data from my browser, it works fine now

**Comment by tasiotas** [comment]
I am still getting this error on 2.3.0

1. Clear cookies
2. Login to dashboard
3. Looks good
4. Refresh page
5. Error
```
[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
```

**Comment by andlil** [comment]
> I am still getting this error on 2.3.0

Yep, something is not right, upgrade to 2.3.1 solves this temporarily since it has to do with the new-version-available.

**Comment by wokalek** [comment]
Had this error too, upgrade to 2.3.1 helped.

**Comment by oscarhermoso** [comment]
@Innei - Would you like to reopen the issue?

**Comment by pclavelloux** [comment]
Some problem here.
I git pull but it seems I'm already up to date

**Comment by mikecao** [comment]
Fixed in v2.4.0.
