### ISSUE TITLE
Upgrading seems to have introduced bugs that cause intermittent failures.

### ISSUE THREAD

**Issue by appotry** [umami-software/umami#2146]
### Describe the Bug

Upgrading seems to have introduced bugs that cause intermittent failures.

docker image: docker.umami.dev/umami-software/umami:mysql-latest

### Database

MySQL

### Relevant log output

Encountered an error message on the website 

```
出现错误。
[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at ep (https://xx.xxx.com/_next/static/chunks/pages/_app-01e3fb586e5843a0.js:1:160)
    at eE (https://xx.xxx.com/_next/static/chunks/pages/_app-01e3fb586e5843a0.js:6:577908)
    at e4 (https://xx.xxx.com/_next/static/chunks/pages/_app-01e3fb586e5843a0.js:6:587655)
    at q (https://xx.xxx.com/_next/static/chunks/pages/websites/%5Bid%5D-549d2825f0ffde57.js:1:4501)
    at ab (https://xx.xxx.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:1:61008)
    at ud (https://xx.xxx.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:1:72894)
    at i (https://xx.xxx.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:1:120462)
    at oO (https://xx.xxx.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:1:99204)
    at https://xx.xxx.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:1:99071
    at oF (https://xx.xxx.com/_next/static/chunks/framework-2c79e2a64abdb08b.js:1:99078)
```

docker log 

```
No pending migrations to apply.

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
Listening on port 3000 url: http://umami:3000
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "umami" at "xxx.xxx.xxx.xxx:3306"

2 migrations found in prisma/migrations


No pending migrations to apply.

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
Listening on port 3000 url: http://umami:3000
PrismaClientValidationError: Argument websiteId for data.websiteId is missing.
Argument session for data.session is missing.

    at Li.validate (/app/node_modules/@prisma/client/runtime/library.js:147:73)
    at dn.createMessage (/app/node_modules/@prisma/client/runtime/library.js:164:1298)
    at /app/node_modules/@prisma/client/runtime/library.js:177:10818
    at Object.runInChildSpan (/app/node_modules/@prisma/client/runtime/library.js:174:1343)
    at t._executeRequest (/app/node_modules/@prisma/client/runtime/library.js:177:10795)
    at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/send.js:214:9) {
  clientVersion: '4.15.0'
}
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "umami" at "xxx.xxx.xxx.xxx:3306"

2 migrations found in prisma/migrations


No pending migrations to apply.

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
Listening on port 3000 url: http://umami:3000
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "umami" at "xxx.xxx.xxx.xxx:3306"

2 migrations found in prisma/migrations


No pending migrations to apply.

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
Listening on port 3000 url: http://umami:3000
```
```


### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

docker

**Comment by mikecao** [comment]
Try this workaround. Open your browser local storage and enter the key umami.version-check with this the value {"version":"2.3.1","time":1690494329049}. This will be fixed in the next version.

**Comment by mikecao** [comment]
Fixed in v2.4.0.

**Comment by appotry** [comment]
@mikecao When I open Umami analytics in a privacy window in version 2.4.0, there is only "umami.auth" in local storage. But I still get the same error as before.
