### ISSUE TITLE
An `id` must be provided to format a message.

### ISSUE THREAD

**Issue by wokalek** [umami-software/umami#2161]
### Describe the Bug

using umami image: `ghcr.io/umami-software/umami:postgresql-v2.3.1`
and `postgres:15-alpine`

```
[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at ep (https://statistic.wokalek.ru/_next/static/chunks/pages/_app-d25b7d6c3a248600.js:1:160)
    at eE (https://statistic.wokalek.ru/_next/static/chunks/pages/_app-d25b7d6c3a248600.js:6:577936)
    at e4 (https://statistic.wokalek.ru/_next/static/chunks/pages/_app-d25b7d6c3a248600.js:6:587683)
    at q (https://statistic.wokalek.ru/_next/static/chunks/pages/websites/%5Bid%5D-549d2825f0ffde57.js:1:4501)
    at ab (https://statistic.wokalek.ru/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:60915)
    at ud (https://statistic.wokalek.ru/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:72801)
    at i (https://statistic.wokalek.ru/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:120370)
    at oO (https://statistic.wokalek.ru/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:99112)
    at https://statistic.wokalek.ru/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98979
    at oF (https://statistic.wokalek.ru/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98986)
```

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

docker

**Comment by CatchWang-YXC** [comment]
I also have this problem

**Comment by wokalek** [comment]
> I also have this problem

Try to update to new 2.4.0 version. For now, I do not have this issue. But before I already had this problem in version 2.3.0 and updated to 2.3.1 and for some time I did not see this problem, but today it appeared again.

**Comment by khromov** [comment]
Also randomly started having this issue on 2.3.0. Works on 2.4.0.

**Comment by acadmin666** [comment]
I also have this problem

**Comment by acadmin666** [comment]
I also have this problem. Before deploying the v1 version with dockers, this problem did not occur. Now I use vercel to deploy the v2 version. This problem occurs. I have a headache and ask for help.

**Comment by wokalek** [comment]
> I also have this problem. Before deploying the v1 version with dockers, this problem did not occur. Now I use vercel to deploy the v2 version. This problem occurs. I have a headache and ask for help.

Try update to 2.4.0.

**Comment by oscarhermoso** [comment]
Fixed in 2.4.0:

https://github.com/umami-software/umami/issues/2113#issuecomment-1657770707

**Comment by franciscao633** [comment]
https://github.com/umami-software/umami/issues/2162#issuecomment-1658581783

**Comment by uncenter** [comment]
Since https://github.com/umami-software/umami/issues/2162 is closed I assume it's safe to close this one too?

**Comment by wokalek** [comment]
> Since #2162 is closed I assume it's safe to close this one too?

I will close myself after a week of checking that the bug does not exist.

**Comment by danielpetrica** [comment]
I also confirm it's resolved with v2.4.0

**Comment by craigconstantine** [comment]
just updated to 2.5.0 (was probably at 2.30 or earlier) and I'm still having this issue. Upon starting Umami (running under pm2) I get this in error log…

```
16:36UTC:root@ns:~/.pm2/logs# cat umami-error.log
warn  - "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
[DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
```

**Comment by roywangdev** [comment]
> just updated to 2.5.0 (was probably at 2.30 or earlier) and I'm still having this issue. Upon starting Umami (running under pm2) I get this in error log…
> 
> ```
> 16:36UTC:root@ns:~/.pm2/logs# cat umami-error.log
> warn  - "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
> [DEPRECATED] Default export is deprecated. Instead use `import { create } from 'zustand'`.
> ```
> 
> View Umami shows…
> 
> ```
> Something went wrong.
> [@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
> r@https://**REDACTED**/_next/static/chunks/pages/_app-37cd5caf026cf410.js:1:155
> m@https://**REDACTED**/_next/static/chunks/pages/_app-37cd5caf026cf410.js:6:545701
> Y@https://**REDACTED**/_next/static/chunks/pages/_app-37cd5caf026cf410.js:6:554727
> Y@[native code]
> R@https://**REDACTED**/_next/static/chunks/pages/dashboard-1a2eb42529af40b3.js:1:4927
> ab@https://**REDACTED**/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:60916
> i@https://**REDACTED**/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:119475
> oO@https://**REDACTED**/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:99113
> @https://**REDACTED**/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98981
> oF@https://**REDACTED**/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:98986
> ox@https://**REDACTED**/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:95740
> oC@https://**REDACTED**/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:96129
> oC@[native code]
> r4@https://**REDACTED**/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:44777
> @https://**REDACTED**/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:93632
> ```

After removing the line "output: 'standalone'" from line 81 of the next.config.js file, I temporarily resolved this issue. However, I'm not sure if it will have any impact on Umami. You can give it a try to ensure your Umami runs smoothly.

**Comment by craigconstantine** [comment]
Strange, on my iMac the Umami interface works fine. On my MacBook, the error persists.

**Comment by thefourcraft** [comment]
@craigconstantine interesting issue, because I have the same one 
On my MacBook, I have this issue, but on my PC and iMac

**Comment by Gkiokan** [comment]
This issue has been reported already on July on version 2.2.0  and seemed to be fixed on 2.3.0.
But unfortunatelly the error does still exist even on the latest build and just appears randomly.

I am using the Docker build, fresh updated and restarted - as of today - still exists and randomly appearing on a couple coworkers browser. 
So maybe the simplest way would be to implement a fallback instead of crashing the whole frontend?

**Comment by thefourcraft** [comment]
<img width="1724" alt="image" src="https://github.com/umami-software/umami/assets/90725541/5f627bb9-80dc-4801-b959-4b948813e330">

2.7.0
