### ISSUE TITLE
/api/send response 400 in v2.6.0

### ISSUE THREAD

**Issue by Paolo97Gll** [umami-software/umami#2247]
### Describe the Bug

With umami v2.6.0 the `/api/send` POST request made by the browser fail with code 400 and message `Cannot read properties of undefined (reading 'includes')`. In umami v2.5.0 and previous this error is not present.

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Edge, but reported also with Powershell `Invoke-WebRequest` and bash `curl`

### How are you deploying your application? (if relevant)

Docker on aarch64 (Raspberry Pi 4)

**Comment by franciscao633** [comment]
Thanks for reporting. This seems to be a duplicate of #2236, or the same root cause. We have a fix and will try to do a release soon.

**Comment by mikecao** [comment]
Fixed in v2.6.1.

**Comment by YiHui-Liu** [comment]
I still get 400 of /api/send in v2.6.2
![image](https://github.com/umami-software/umami/assets/30190271/aca831ae-5820-4a7d-b924-728bd4298376)
