### ISSUE TITLE
2.6.1 TRACKER_SCRIPT_NAME is not working for docker

### ISSUE THREAD

**Issue by MFYDev** [umami-software/umami#2252]
### Describe the Bug

Set TRACKER_SCRIPT_NAME in docker fresh install and use it behind nginx proxy.

It will show that domain/trackerscipt 404 error

### Database

PostgreSQL

**Comment by MFYDev** [comment]
Also, use the source installation, cannot connect to MySQL 8.0 on the localdatabase, can confirm the database url is fully correct

<img width="516" alt="image" src="https://github.com/umami-software/umami/assets/53750381/30d70239-3717-40c2-b1b3-b034218d4cdc">

**Comment by MFYDev** [comment]
Solved by adding a one more reverse proxy on nginx, but if it can be corrected in the source code that will be great

**Comment by rebron1900** [comment]
+1，
I also encountered this problem.

**Comment by mikecao** [comment]
We believe we've found the issue. Will release another hotfix soon.

**Comment by mikecao** [comment]
Fixed in v2.6.2.

**Comment by MFYDev** [comment]
Hi, this is not fixed, just upgraded to the latest docker image and it shows this error:
Failed to proxy https://192.168.144.3:3000/script.js Error: write EPROTO 583BAD55807F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -71,
  code: 'EPROTO',
  syscall: 'write'
}

**Comment by mikecao** [comment]
@MFYDev That error looks unrelated to the app and coming from a proxy server maybe?
