### ISSUE TITLE
Broken channel attribution: no Paid Search

### ISSUE THREAD

**Issue by tsykin** [umami-software/umami#3264]
### Describe the Bug

When exploring website traffic per channels, it seems that Paid Search is being attributed to Direct or Organic Search.

Specifically, I use Google Ads with the following UTM (sampled values except for source & medium): 

```
domain.com?utm_source=google&utm_medium=cpc&utm_campaign=12345&utm_source_platform=google_ads&gad_source=1&gclid=UTICj0XQLiA
```

This traffic is being recorded in Umami, but it's being attributed to the wrong Channel. Since `source=google` and `medium=cpc`, this traffic should be attributed to Paid Search channel, but I have 0 visitors from that Channel according to Umami's dashboard.

Oher tools, specifically Google Analytics 4 is identifying this traffic as:
- source/medium = google/cpc
- Defaul Channel Grouping = Paid Search

Here are some screenshots for clarity. Time range is the same between tools, no active filters.

![Screenshot of Umami dashboard](https://github.com/user-attachments/assets/61eb3220-26b9-494d-95f7-2b152e08c86b)

![Screenshot of GA4 dashboard](https://github.com/user-attachments/assets/1a879bcf-8db0-48c4-b940-deb03588ba2f)

P.S. I know that GA4 is reporting 5+ times less users, my issue is specifically about Umami's broken channels attributions.

Code responsible for attributing traffic to a specific channel appears to be here: 

```
umami/src/app/api/websites/[websiteId]/metrics/route.ts#getChannels
```

### Database

PostgreSQL

### Relevant log output

```shell
No relevant deploy logs found.
```

### Which Umami version are you using? (if relevant)

v2.16.1

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Railway

**Comment by tsykin** [comment]
Upon further inspection, I noticed that even in the official [Umami Demo Dashboard](https://eu.umami.is/share/LGazGOecbDtaIwDr/umami.is), there are no visitors from any Paid channel on the dashboard, despite the clear presence of paid traffic.

[Umami Demo, query params report](https://eu.umami.is/share/LGazGOecbDtaIwDr/umami.is?view=query)

[Umami Demo, channels report](https://eu.umami.is/share/LGazGOecbDtaIwDr/umami.is?view=channel)

Specifically, there's traffic with these parameters:
```
utm_source=facebook&utm_medium=cpc&utm_campaign=website_analytics
```

However, this traffic is not being attributed to either the "Paid Social" or the "Paid Ads" channel.

**Comment by mikecao** [comment]
Fixed in v2.17.0.

**Comment by dragosidle** [comment]
Hi! I think the issue persists, at least on my end. I've been running a google search ad campaign on my website and the paid search channels is empty still. Running Plausible as well to look for differences. Measurements are from this morning until now.

![Image](https://github.com/user-attachments/assets/a4cd2d2c-1ed0-4b94-8786-4739f77b96e3)

![Image](https://github.com/user-attachments/assets/7133fd35-56cb-44f3-9ff7-7a06cf071564)

**Comment by tsykin** [comment]
Yes, indeed the issue persists and was not fixed in v2.17.0.
The attribution to paid channels is still broken even though in Query Parameters report traffic with `source/medum` = `google/cpc` is clearly visible.

@mikecao Can you please look into that? 

The solution might be to modify this function:

```
umami/src/app/api/websites/[websiteId]/metrics/route.ts#getChannels
```

**Comment by mikecao** [comment]
@dragosidle can you post some of the raw query parameters?

**Comment by dragosidle** [comment]
> [@dragosidle](https://github.com/dragosidle) can you post some of the raw query parameters?

Should I look for something specific in the network tab? Not quite sure how I can help

**Comment by tsykin** [comment]
> > [@dragosidle](https://github.com/dragosidle) can you post some of the raw query parameters?
> 
> Should I look for something specific in the network tab? Not quite sure how I can help

I think he wants you to share examples of which query parameters are being attributed to Paid Search in Plausible and not being properly attributed in Umami.

This is my example:

```
domain.com?utm_source=google&utm_medium=cpc&utm_campaign=12345&utm_source_platform=google_ads&gad_source=1&gclid=UTICj0XQLiA
```

You can find raw query parameters in Umami Website Dashboard > More > Query parameters > Raw

**Comment by dragosidle** [comment]
Thanks @tsykin, I hope this is correct. I'd like to add the chosen timeframe only shows ads traffic. The website gets 0 traffic usually, unless a search ad campaign is running.

gad_source=1&gclid=Cj0KCQjwhMq-BhCFARIsAGvo0KeF0cVnanTx_fP-ba3Sby1a_EfenqiPqfIrHp51-sQUtGwRceI-uSMaArOSEALw_wcB

gad_source=1&gclid=EAIaIQobChMIw5jHkvCGjAMVU6ODBx0XVDLgEAAYASAEEgJvTfD_BwE

gad_source=1&gclid=EAIaIQobChMIha2vndWKjAMV7guiAx022wyxEAAYASAEEgK4XfD_BwE

**Comment by tsykin** [comment]
@dragosidle Are you sure you have attached the full raw query?

The ones that you attached don't contain two main parameters: source & medium. 

The issue discussed still persists since `gclid` and/or `gad_source` parameters can be used to attribute traffic to Paid Search channel, but I would still suggest you use source and medium parameters in your Paid campaigns.

**Comment by ka0tik0** [comment]
> [@tsykin](https://github.com/tsykin) It looks like it's an ordering issue. It's matching other criteria before it gets to the paid ads block. Will get this fixed.

Any new news regarding a solution to this problem?

**Comment by tsykin** [comment]
I have created another issue due to new findings: [#3403](https://github.com/umami-software/umami/issues/3403)

There's already a PR from me fixing this issue: [#3406](https://github.com/umami-software/umami/pull/3406)
