### ISSUE TITLE
Direct visitors are missing on Channels (3.0.1)

### ISSUE THREAD

**Issue by renatoyamazaki** [umami-software/umami#3789]
<img width="1304" height="410" alt="Image" src="https://github.com/user-attachments/assets/f640d9df-d51b-40eb-9d4e-ecf32b76624f" />
<img width="1340" height="553" alt="Image" src="https://github.com/user-attachments/assets/fb70ff95-9b0e-48ad-9ca4-f7b928cf0b57" />

### Describe the Bug

After upgrading from 2.19.0 to 3.0.1 the direct visitors on Channels are missing. 

### Database

PostgreSQL

### Relevant log output

```shell

```

### Which Umami version are you using? (if relevant)

3.0.1

### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Docker

**Comment by mikecao** [comment]
Fixed in v3.0.2.

**Comment by robinparisi** [comment]
Hi, the bug seems not fully fixed. In Umami 3.0.3 (docker + postgres 15), direct traffic (379 events in my case) doesn't appear in the Channels tab.

Root cause: When there's no referrer, Prisma inserts NULL into referrer_domain (as expected for a nullable String? field in schema.prisma). However, [getChannelMetrics.ts](https://github.com/umami-software/umami/blob/master/src/queries/sql/getChannelMetrics.ts) checks for an empty string:

```
when referrer_domain = '' and url_query = '' then 'direct'
```

Since NULL = '' evaluates to FALSE in SQL, direct traffic is never classified as "Direct" and falls into the else '' branch, then gets excluded by where x != ''.

Confirmed on my server with:

```
SELECT
  COUNT(*) FILTER (WHERE referrer_domain IS NULL) as nb_null,
  COUNT(*) FILTER (WHERE referrer_domain = '') as nb_empty
FROM website_event;
-- Result: nb_null = 379, nb_empty = 0
```
