### ISSUE TITLE
Timezone error in v3.0.1 – “Last 24h” & custom range shift data +5h and exclude valid events

### ISSUE THREAD

**Issue by bradbeshaw** [umami-software/umami#3810]
### Description

The timezone window logic is still incorrect in v3.0.1.

Data is displayed correctly in Realtime view, but **“Last 24 hours” and all custom date ranges shift timestamps +5 hours**, which makes the data appear to be in the future. As a result, valid analytics fall outside the window and are either missing completely or shown at incorrect hours.

### Environment
- Umami version: **3.0.1**
- Server OS timezone: **America/New_York (EST, UTC–05:00)**
- PostgreSQL timezone: **America/New_York**
- Node runtime: restarted after timezone correction
- Browser/UI timezone: **America/New_York**
- Also tested with: **set TZ=UTC before `npm start` – issue persists**

### Evidence
Realtime tracking displays correctly.

Custom range chart example (should show data from 1–4 PM local, instead shows 6 PM–9 PM):

<img width="1592" height="944" alt="Image" src="https://github.com/user-attachments/assets/1d0f4f22-259d-4bfd-b74c-98a08919cabd" />

### Database

PostgreSQL

### Relevant log output

```shell

```

### Which Umami version are you using? (if relevant)

3.0.1

### Which browser are you using? (if relevant)

Chrome, Edge, Firefox

### How are you deploying your application? (if relevant)

node

**Comment by franciscao633** [comment]
This may be related to #3781. Also wondering is this only an issue on the last 24 hours/custom time frames, but different time frames are ok?

**Comment by eroc1990** [comment]
This same thing is happening to me, except across any range. No matter which graph I'm looking at, the graph is missing the first four hours of whichever bar graph I'm looking at. This happens in the normal hourly views for both real time and compare data.

**Comment by KevinYouu** [comment]
I have the same problem, always missing 8 hours

**Comment by markwoon** [comment]
Same here, with 8 hour gap.  Sounds like a UTC timezone conversion issue.

**Comment by bradbeshaw** [comment]
This 'deal-breaker' debilitating bug has not been repaired?

**Comment by eroc1990** [comment]
Seriously. How has this not been addressed? Still seeing a +5h offset.

**Comment by yandujun363** [comment]
The time zone issue is still unresolved. My time zone is UTC+8, but the time displayed on the statistics page is 8 hours behind, so I still need to add 8 hours manually. However, the real-time interface displays the time correctly.

<img width="1903" height="1078" alt="Image" src="https://github.com/user-attachments/assets/6b1f1d3d-eff3-4f5e-841b-ee4d41429fc8" />

**Comment by azamara** [comment]
This seems to be related to a Prisma `@prisma/adapter-pg` bug where Date objects are stored incorrectly when the PostgreSQL session timezone isn't UTC.
- https://github.com/prisma/prisma/issues/28629

**Workaround**

Add timezone option to `DATABASE_URL`:

```diff
-DATABASE_URL="postgresql://user:pass@host:5432/dbname
+DATABASE_URL="postgresql://user:pass@host:5432/dbname?options=-c%20timezone%3DUTC"
```

**Comment by yandujun363** [comment]
I'll throw the timezone-related code to the AI for analysis. When I have time, I'll open a test PR to take a look.

Looking at your code, I found the **key issue**! The problem is in the **ClickHouse query layer**, not the timezone conversion logic.

## Problem Location:

### 1. **ClickHouse timezone handling function has issues**
Look at the `getDateSQL` function in `src/lib/clickhouse.ts`:

```typescript
function getDateSQL(field: string, unit: string, timezone?: string) {
  if (timezone) {
    return `toDateTime(date_trunc('${unit}', ${field}, '${timezone}'))`; // ❌ Problem here
  }
  return `toDateTime(date_trunc('${unit}', ${field}))`;
}
```

### 2. **ClickHouse's date_trunc function timezone handling**
In ClickHouse, the timezone parameter of the `date_trunc` function affects **where the truncation happens**, but doesn't change **the timezone itself**.

**Example:**
```sql
-- Assume created_at = '2026-01-13 02:00:00 UTC'
-- Your timezone = 'Asia/Shanghai' (UTC+8)

-- Wrong understanding:
date_trunc('hour', created_at, 'Asia/Shanghai')
-- You think: 02:00 UTC + 8 hours = 10:00 then truncate = 10:00
-- Actual: On 02:00 UTC, truncate based on Asia/Shanghai timezone rules = 02:00 (no timezone conversion!)

-- Should use:
toTimeZone(date_trunc('hour', created_at), 'Asia/Shanghai')
-- Or:
date_trunc('hour', toTimeZone(created_at, 'Asia/Shanghai'))
```

## Specific Fix Solutions:

### Fix Solution A: Modify `getDateSQL` function
```typescript
// src/lib/clickhouse.ts
function getDateSQL(field: string, unit: string, timezone?: string) {
  if (timezone) {
    // ❌ Wrong (current code)
    // return `toDateTime(date_trunc('${unit}', ${field}, '${timezone}'))`;
    
    // ✅ Correct solution 1: Convert timezone first, then truncate
    return `date_trunc('${unit}', toTimeZone(${field}, '${timezone}'))`;
    
    // ✅ Correct solution 2: Truncate then convert timezone
    // return `toTimeZone(date_trunc('${unit}', ${field}), '${timezone}')`;
  }
  return `toDateTime(date_trunc('${unit}', ${field}))`;
}
```

### Fix Solution B: Check all places using time fields
Also need to check `getDateStringSQL` function:

```typescript
function getDateStringSQL(data: any, unit: string = 'utc', timezone?: string) {
  if (timezone) {
    // ❌ Might also have issues
    // return `formatDateTime(${data}, '${CLICKHOUSE_DATE_FORMATS[unit]}', '${timezone}')`;
    
    // ✅ Ensure data is already converted to timezone
    return `formatDateTime(toTimeZone(${data}, '${timezone}'), '${CLICKHOUSE_DATE_FORMATS[unit]}')`;
  }
  return `formatDateTime(${data}, '${CLICKHOUSE_DATE_FORMATS[unit]}')`;
}
```

## Verify the Problem:

Test in ClickHouse:

```sql
-- Test current logic
SELECT 
  -- Original UTC time
  toDateTime('2026-01-13 02:00:00') as utc_time,
  
  -- Current wrong logic
  date_trunc('hour', toDateTime('2026-01-13 02:00:00'), 'Asia/Shanghai') as current_logic,
  
  -- Should be logic
  toTimeZone(date_trunc('hour', toDateTime('2026-01-13 02:00:00')), 'Asia/Shanghai') as should_be,
  
  -- Or
  date_trunc('hour', toTimeZone(toDateTime('2026-01-13 02:00:00'), 'Asia/Shanghai')) as should_be_2;
```

## View Actual Generated SQL:

You need to find the code that generates statistical queries (likely in `src/queries/clickhouse/` directory):

```bash
# Search for places using getDateSQL
grep -r "getDateSQL" src/

# Search for code generating pageviews queries
grep -r "pageviews.*query" src/queries/
```

## Temporary Verification:

Modify `src/lib/clickhouse.ts` file to verify:

```typescript
// Temporarily add logs to view generated SQL
function getDateSQL(field: string, unit: string, timezone?: string) {
  let sql;
  if (timezone) {
    sql = `date_trunc('${unit}', toTimeZone(${field}, '${timezone}'))`;
    console.log('📅 getDateSQL:', { field, unit, timezone, sql }); // Add log
  } else {
    sql = `toDateTime(date_trunc('${unit}', ${field}))`;
  }
  return sql;
}
```

Then call the API and check console output for SQL.

## Complete Fix Steps:

1. **Modify `src/lib/clickhouse.ts`**:
   ```typescript
   // Fix getDateSQL
   function getDateSQL(field: string, unit: string, timezone?: string) {
     if (timezone) {
       // Solution 1: Convert timezone first then truncate (recommended)
       return `date_trunc('${unit}', toTimeZone(${field}, '${timezone}'))`;
       
       // Solution 2: Or use ClickHouse's timezone conversion
       // return `toTimeZone(date_trunc('${unit}', ${field}), '${timezone}')`;
     }
     return `toDateTime(date_trunc('${unit}', ${field}))`;
   }
   
   // Fix getDateStringSQL
   function getDateStringSQL(data: any, unit: string = 'utc', timezone?: string) {
     if (timezone) {
       return `formatDateTime(toTimeZone(${data}, '${timezone}'), '${CLICKHOUSE_DATE_FORMATS[unit]}')`;
     }
     return `formatDateTime(${data}, '${CLICKHOUSE_DATE_FORMATS[unit]}')`;
   }
   ```

2. **Check all statistical queries**:
   Ensure all queries using time fields correctly convert timezones.

3. **Test verification**:
   ```javascript
   // Call API to verify
   const response1 = await fetch('/api/pageviews?...&timezone=Asia/Shanghai');
   const response2 = await fetch('/api/pageviews?...&timezone=UTC');
   
   // A visit at Beijing time 10:00 should:
   // - UTC return: 02:00
   // - Asia/Shanghai return: 10:00
   ```

## Root Cause Summary:

**ClickHouse's `date_trunc(field, unit, timezone)` function**:
- It only **considers timezone rules during truncation** (like week start day), but **doesn't convert timezone**
- To actually convert timezone, you need to use the `toTimeZone()` function

This is why the API always returns times 8 hours early - the time is correctly truncated but remains in UTC timezone, not converted to the target timezone.

**Comment by nicanordlc** [comment]
🙏

**Comment by bradbeshaw** [comment]
Is this solved in the Umami installation, or is this modification manually performed in PostgreSql installation post install?

**Comment by tmanok** [comment]
IDK why this issue is closed, it's still a problem in the traffic section on a Fresh install of 3.0.3. 

Thank you for making this application, I am a happy new user and grateful to have anything of this quality. Just noting that this bug is still present.

**Comment by linowski** [comment]
Same here. I have proper TZ in docker, postegre, server, ENV, and confirmed in Umami settings, and also getting +3 hour difference in the today graph. 

<img width="411" height="762" alt="Image" src="https://github.com/user-attachments/assets/714e42da-1c6d-4888-bf38-e2a616ae6e8f" /> (Current time 3pm EDT, and showing up as 6pm in the Today graph).

**Comment by E021ntox** [comment]
Still not fixed.
